import Character from './Character.js'
import Bowman from './Bowman.js'
import Swordsman from './Swordsman.js'
import Magician from './Magician.js'
import Undead from './Undead.js'
import Zombie from './Zombie.js'
import Daemon from './Daemon.js'
